
- name: Create directory
  file:
    path: ~/backend
    state: directory

- name: Copy backend files to EC2 server
  copy:
    src: ~/project/backend/dist
    dest: ~/backend

- name: Check backend state
  shell: ls -la
  register: backfolder

- name: print backfolder
  debug:
    msg: "{{ backfolder.stdout_lines }}"


- name: Running backend
  shell: |
    cd ~/backend
    ls -la
    pm2 start main.js -f 